version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bankcards-postgres
    restart: always
    ports:
      - "7777:5432"
    environment:
      POSTGRES_DB: card
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: drakon0409
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: bankcards-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/card
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: drakon0409
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: true
    command: ["./mvnw", "spring-boot:run"]

volumes:
  pgdata: