server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:7777/card
    username: postgres
    password: drakon0409
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none     
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: this-is-a-very-long-super-secure-secret-12345678
  expiration: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
